name: qr_generator
description: Dart package to manage {Feature} data and domain layers.
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Scope Packages
  errors:
    git:
      url: git://github.com/NoScopeDevs/errors

  dartz: ^0.10.0-nullsafety.1
  dio: ^4.0.0
  equatable: ^2.0.0
  uuid: ^3.0.3 
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  # code generators
  build_runner: null
  freezed: ^0.14.1+1
  json_serializable: ^4.1.0

  # testing
  mockito: ^5.0.3
  test: ^1.16.8

  # static analysis
  very_good_analysis: ^2.0.0