name: qr_generator_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  qr_generator:
    path: packages/qr_generator
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_barcode_scanner: ^2.0.0-nullsafety.0
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.16.0
  freezed_annotation: ^0.14.1
  get_it: ^6.0.0
  i18n_extension: ^4.0.2
  qr_flutter: ^4.0.0
  very_good_analysis: ^2.0.0

dev_dependencies:
  # flutter_driver:
  #   sdk: flutter
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  build_runner: null
  freezed: ^0.14.1+2
  mocktail: ^0.1.1
  # test: ^1.16.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: digital7
      fonts:
        - asset: fonts/digital-7.ttf
